### PR TITLE
fixing add function (codingTrainLive)!

### PR DESCRIPTION
**Pull request by idantur**

### CODE REVIEW

**Comment by shiffman** [comment]
I appreciate this fix, but I think (even if backwards), the convention I'm using in the videos is `i` for rows and `j` for columns? Happy to re-open if I'm confused!

**Comment by idantur** [comment]
I actually did not do nothing to the code I just change the variables name ( "i" to "j" and "j" to "i").

your code before the "change" :
```javascript
   for (let i = 0; i < this.rows; i++) {
        for (let j = 0; j < this.cols; j++) {
          this.data[i][j] += n.data[i][j];
        }
    }
```
the code after :
```javascript
for (let j = 0; j < this.rows; j++) {
         for (let i = 0; i < this.cols; i++) {
           this.data[j][i] += n.data[j][i];
        }
    }
```

**I did this "change" because I saw that no one is posting a pull request and I wanted that you will start the tutorial.**


note :
- [ ] I'm 13 years old from Israel so my English is not very good. love your videos by the way 👍 

question:
- [ ] can you do a coding challenge about the game Tic Tac Toe?

**Comment by shiffman** [comment]
Your English is great! Of course, now I get why you made the pull request, thank you again!

Thank you for writing and I love the idea of doing tic tac toe for sure!

**Comment by idantur** [comment]
here is a few links that you can use if you will want to do the challenge: 
 - [Tic-tac-toe wikipedia page](https://en.wikipedia.org/wiki/Tic-tac-toe)
 - [Tic-tac-toe algorithm page](https://medium.freecodecamp.org/how-to-make-your-tic-tac-toe-game-unbeatable-by-using-the-minimax-algorithm-9d690bad4b37)
 - [Tic-tac-toe for playing](https://playtictactoe.org/)

thank's , Idan Turkenits from Israel :)

**Pull request closed without merging**
