### PR TITLE
update matrix constructor to use array fill function

### PR DESCRIPTION
**Pull request by philaturner**
tidied up the constructor a little bit, plus I've never done a pull request before

### CODE REVIEW

**Comment by shiffman** [comment]
Apologies, can you resolve the conflicts? I love this change, but since I haven't explained `fill()` in a video yet, I wonder if it will be confusing? Or maybe this means I better just get to explaining it.

**Comment by philaturner** [comment]
Conflicts resolved now.  Might be a good to introduce it in a video as you could refactor quite a bit using similar methods, that said, I know you like things to explicit and readable so your call on if you want to merge or not :)

**Comment by shiffman** [comment]
The question around adding `fill()` is also addressed in #25.

**Comment by shiffman** [comment]
Merging this live on air! And noting to make a video about `fill()` here: https://github.com/CodingTrain/Rainbow-Topics/issues/515

**Pull request merged**
