### PR TITLE
Map improvements and using map instead of 2 nested for loops

### PR DESCRIPTION
**Pull request by mdatsev**
- ### Made map pass the row and column to the callback function.
Important: The indices are 0-based, I don't know if this or 1-based is appropriate. Discuss below. 
- ### Added tests for map with row and column
- ### Using map instead of 2 nested for loops in the methods.
This makes the code less repetitive, clearer and more concise, but since it's different from the videos this may be a bit problematic for some.

### CODE REVIEW

**Comment by shiffman** [comment]
I'm slightly afraid to merge this since it will make the code so different from how it is in the videos! But I love this improvement and the use of ES6 `=>`. Maybe it's best for me to publish the original library code in the state it is now at https://github.com/CodingTrain/Rainbow-Code to match the videos then the improvements can live here?

**Comment by philaturner** [comment]
Might make a good video once you're a the end of your series to ES6-ify it all based on community input :)

**Comment by mdatsev** [comment]
@shiffman That's a good idea, put the code exactly as in the videos there, so people can easily follow and in this repo any improvements. Later on if you decide they are worth going over in a video, you could make use of them there as well. Besides a few days ago I searched the code there and I couldn't find it, and this repo is not linked in the description of at least some of the videos which I looked at and only

> Source Code for the all Video Lessons: https://github.com/CodingTrain/Rainbow-Code

so the code should be there in any case I think. The other thing I thought about is making a branch for that purpose, because this might make merging stuff over easier but maybe more confusing for some.

**Comment by shiffman** [comment]
The original source code as matching the videos (I think) is now:

https://github.com/CodingTrain/Rainbow-Code/tree/master/Courses/natureofcode/10.18-toy_neural_network

(Will happily accept any pull requests to README etc to make this more clear.)

So this library can go forth and be improved. . .

**Pull request merged**
