### PR TITLE
Use ES6 export and import functions to not require a if check

### PR DESCRIPTION
**Pull request by MTRNord**
~~The tests are failing as Jest does NOT understand a es6 import yet :( Jest currently would require you to transpile the Code before testing which in my eyes is overkill for this project. But you might consider this syntax for later projects that run in browser or a transpiler like "Babel" makes sense to use.~~

The above text was wrong. I don't need to add the full babel transpiler to do this but a part of it. I added the default support of babel and a config file. Jest automagicly transpiles the code now and the tests do pass without altering the main code.

Explenation:

The `export default` is the ES6 syntax of `module.exports` and should be used. It is browser and nodejs compatible.

The import is basicly (not exactly) the same but new Version of require and should get used nowerdays. It is also browser and nodejs compatible.

The ` type="module"` atribute is required for browsers to tell them that you are currently using new ES6 syntax.

These changes make it able for you to not have that if at the end and not have to rely on any workarounds.

Signed-off-by: MTRNord <mtrnord1@gmail.com>

### CODE REVIEW

**Comment by shiffman** [comment]
Thank you for this, it's super helpful! I wonder if I should do a video about this before merging as other contributors might be confused seeing the new syntax?

I'm still unclear . . is babel required? For simplicity, I might prefer to leave it out even if it makes the code not work on old browsers?

**Comment by MTRNord** [comment]
No it isnt required as it self. Jest uses it internaly to test es6 modules. But Jest requires you to have a babel config and a preset. (it is written also in the getting started doc of Jest).

Babel does not get run when using it in the Browser or using this as some dependency. Only jest runs it internaly so that they understand the code

**Comment by MTRNord** [comment]
The Browsers itself understand it by telling them it is a es6 module via the type attribute. (except older Internet Explorer of course).

**Comment by MTRNord** [comment]
Also worth noting in the newest nodejs (I think already a few versions currently. But I don't know a exact version number since when) this es6 syntax is supported without needing to use babel. More information can be found under the term "es2016".

The babel usage in this PR is simply because Jest doesn't support ES6 without it :(

**Comment by MTRNord** [comment]
> I wonder if I should do a video about this before merging as other contributors might be confused seeing the new syntax?

I guess that makes sense to do. Even as the syntax is very similiar to the old one. I personaly don't think it requires a full video itself but propably a note on it next time you work on the code. (But I have to say I am very advanced in coding so I might missjudge on how different this code might be for starters)

**Comment by MTRNord** [comment]
@meiamsome I cant agree with your firefox argument. My firefox (newest version) does support this. I even tested this in firefox. But I do agree this is not a perfect solution yet. The full pr was more of the purpose to know this exists

**Pull request closed without merging**
