### PR TITLE
Add scalar product test.

### PR DESCRIPTION
**Pull request by musabkilic**

### CODE REVIEW

**Comment by shiffman** [comment]
Apologies, new conflicts!

**Comment by musabkilic** [comment]
Well, there is matrix+matrix test now :). Let's try another thing then.

**Comment by musabkilic** [comment]
Solved conflicts. @shiffman

**Comment by shiffman** [comment]
Thank you!

**Comment by musabkilic** [comment]
My pleasure. I love all of your work and videos. Keep up the good work!

**Pull request merged**
