### PR TITLE
Multilayer Neural Network

### PR DESCRIPTION
**Pull request by MkLahane**
Created a multilayer neural network class  which uses the matrix library in this repository for matrix operations. Some functionality is changed like you need to pass only 2 parameters(number of input nodes, number of output nodes) to the constructor of the neural network and for adding a hidden layer you need to call the function addHiddenLayer(number of neurons) for adding a hiddenLayer to your neural network and before training and after calling all addHiddenLayer function calls you need to call the config() function.

### CODE REVIEW

**Comment by xxMrPHDxx** [comment]
You may be interested on [this](https://raw.githubusercontent.com/Neural-Network-JS/Number-To-Image/master/lib/nn.js)

**Comment by MkLahane** [comment]
Wow, it is really great. Your code is quite optimised and is much more short and precise than mine.

**Comment by xxMrPHDxx** [comment]
Thank you. But I'm not really sure that it will produce the expected result. Yours seems much better and promising though.

**Comment by AR-234** [comment]
Haven't looked in here before i've wrote my Version, i've merged it into the nn.js file, so it's not breaking the examples, but i like your approach. And i've broke the serialize and have no clue how to fix it..
Maybe somebody of you know a way to fix it? [link](https://github.com/AR-234/Toy-Neural-Network-JS/blob/master/lib/nn.js)

@xxMrPHDxx yours looks really awesome!

**Comment by xxMrPHDxx** [comment]
You can try to use this `serialize` function instead

```
serialize() {
   let cache = [];
   return JSON.stringify(this,(key, value) => {
      if (typeof value === 'object' && value !== null) {
         if (cache.indexOf(value) !== -1) {
            // Circular reference found, discard key
            return;
         }
         // Store value in our collection
         cache.push(value);
      }
      return value;
   });
   cache = null;
}
```

**Comment by shiffman** [comment]
Thank you so much for this contribution and discussion! At the moment I prefer #61 and keeping just a single `NeuralNetwork` class as well as adding a `Layer` class.

**Pull request closed without merging**
